version: "3.8"

services:
    db:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
    app:
        build:
            context: .
            dockerfile: ./Dockerfile
        command: bash -c "rm -f tmp/pids/server.pid && rails db:create db:migrate db:seed && rails server -b '0.0.0.0'"
        volumes:
            - "./aplicacao:/home"
        ports:
            - 3000:3000
        depends_on:
            - db

    nginx:
        image: nginx
        ports:
            - 80:80
        volumes:
            - "./nginx.conf/:/etc/nginx/nginx.conf"
        depends_on:
            - app
